version: 2.1

jobs:
  update_data:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install beautifulsoup4 requests pprint faster_than_requests google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > credentials.json
            python docs.py
            python get_ranking.py
            python ranking_br.py
            python statistics.py
      - run:
          name: Update granblue
          command: |
            . venv/bin/activate
            cd granblue
            python ranking_br.py
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "joaorbezerra@hotmail.com"
            git config user.name "tournamentapibot"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git add .
            git commit -am "[skip ci] Updating Data ${DATE_TODAY}" --allow-empty
            git push origin master

workflows:
  daily_data_update:
    triggers:
      - schedule:
          cron: "0 1,7,13,19 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_data
